- type: department
  id: CEGuard
  name: department-CEGuard
  description: department-CEGuard-desc
  weight: 9
  color: "#576384"
  editorHidden: false
  roles:
  - CEGuardCommander
  #- CEInvestigator
  - CEGuard

- type: department
  id: CETavern
  name: department-CETavern
  description: department-CETavern-desc
  weight: 0
  color: "#37f431"
  editorHidden: false
  roles:
  - CETavernmaster
  - CEChef
  #- CEBartender
  #- CEFarmer

- type: department
  id: CEEngineering
  name: department-CEEngineering
  description: department-CEEngineering-desc
  weight: 8
  color: "#ccaa44"
  editorHidden: false
  roles:
  - CEBrigadier
  - CETechnician

- type: department
  id: CECitizens
  name: department-CECitizens
  description: department-CECitizens-desc
  weight: -1
  color: "#b3b3b3"
  editorHidden: false
  roles:
  - CETownfolk
  - CEBard
  - CETailorMerchant
  - CEPharmacistMerchant
  - CEHomeGoodsMerchant
