- type: job
  id: CEBartender
  setPreference: true
  name: ce-job-name-bartender
  description: ce-job-desc-bartender
  playTimeTracker: CEJobBartender
  #startingGear: CEGuardGear
  icon: CEJobIconBartender
  supervisors: ce-job-supervisors-empire
  canBeAntag: true

#- type: startingGear
#  id: CEGuardGear
#  equipment:
#    keys: CEKeyRingGuard
#    belt: CEWalletFilledTest
