- type: job
  id: CEChef
  setPreference: true
  name: ce-job-name-chef
  description: ce-job-desc-chef
  playTimeTracker: CEJobChef
  #startingGear: CEGuardGear
  icon: CEJobIconChef
  supervisors: ce-job-supervisors-empire
  canBeAntag: true

#- type: startingGear
#  id: CEGuardGear
#  equipment:
#    keys: CEKeyRingGuard
#    belt: CEWalletFilledTest
