- type: job
  id: CEFarmer
  setPreference: true
  name: ce-job-name-farmer
  description: ce-job-desc-farmer
  playTimeTracker: CEJobFarmer
  #startingGear: CEGuardGear
  icon: CEJobIconFarmer
  supervisors: ce-job-supervisors-empire
  canBeAntag: true

#- type: startingGear
#  id: CEGuardGear
#  equipment:
#    keys: CEKeyRingGuard
#    belt: CEWalletFilledTest
