- type: job
  id: CETavernmaster
  setPreference: true
  name: ce-job-name-tavernmaster
  description: ce-job-desc-tavernmaster
  playTimeTracker: CEJobTavernmaster
  #startingGear: CEGuardGear
  icon: CEJobIconTavernmaster
  supervisors: ce-job-supervisors-empire
  requireAdminNotify: true
  joinNotifyCrew: true
  canBeAntag: true
  weight: 2

#- type: startingGear
#  id: CEGuardGear
#  equipment:
#    keys: CEKeyRingGuard
#    belt: CEWalletFilledTest
